### ISSUE TITLE
If agg has not any arguments, it can show the latest search result.

### ISSUE THREAD

**Issue by acgtyrant** [lilydjwg/search-and-view#3]
I advise.

If you have no interest, I will try my best to make a pull request...

**Comment by lilydjwg** [comment]
`agg` is for searching, and `agv` is for viewing. I'd rather not mix them up. Typing `agg` means you want to _search_ for something, so it's surprising you see the previous results (and they may be stale as no actual search happens).

**Comment by acgtyrant** [comment]
I am doubting that we are not discussing the same topic. If we execute `agg` immediately, it return the latest search result, so that we do not need input the same keyword again. I do not understand what is wrong with this.

**Comment by lilydjwg** [comment]
If you want to redo the last search, it's OK but hard to implement with shell scripts. If you mean to _view_ the last search results, that's misleading because the semantics of this command changes.

**Comment by acgtyrant** [comment]
OK, I will redo the last search in the shell later while I can use `ctrl-r` to repeat conveniently.
