### ISSUE TITLE
agg 会一直记住不存在的搜索路径

### ISSUE THREAD

**Issue by acgtyrant** [lilydjwg/search-and-view#7]
大概。

我曾执行 `agg size() == 0`, 当时忘记加上双引号，结果后来不管搜什么，均返回 `agg:8: = not found`, 且每次搜索都会递增数字，我猜 `agg` 把 `=` 当成搜索路径并记住了。

**Comment by lilydjwg** [comment]
Run `unfunction agg size`. See [this zsh-users thread](http://www.zsh.org/mla/users/2015/msg01312.html).
